---
version: 2
updates:
  - package-ecosystem: pip   # See documentation for possible values
    directory: /   # Location of package manifests
    schedule:
      interval: weekly
      day: monday
      time: '02:00'
      timezone: America/New_York
    labels:
      - dependencies
    target-branch: master
    assignees:
        - "danner26"
