---
name: Validate definitions
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint YAML files
        run: |
          yamllint --format github --strict \
            device-types/ module-types/
      - name: Format YAML files (yamlfmt)
        run: |
          pre-commit run --config .pre-commit-yamlfmt-config.yaml --all-files
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Process changes
        if: steps.changes.outputs.changed > 0
        uses: actions/github-script@v3
        with:
          script: core.setFailed('YAML formatted detected changes. All files must conform to pre-commit/yamlfmt formatting. Utilize pre-commit run to fix issue.')
      - name: Run tests
        run: pytest --tb=short -v