---
name: Validate definitions
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint YAML files
        run: |
          yamllint --format github --strict \
            device-types/ module-types/
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Format YAML files (hooks)
        run: |
          pre-commit run --config .pre-commit-hooks-config.yaml --all-files
      - name: Format YAML files (yamlfmt)
        run: |
          pre-commit run --config .pre-commit-yamlfmt-config.yaml --all-files
  test:
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install pytest plugin to annotate failures in GitHub
        run: pip install pytest-github-actions-annotate-failures
      - name: Run Test Cases
        id: pytest
        run: pytest --tb=short -v
