---
name: Validate definitions

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest --tb=line -v
      - name: lint YAML files
        run: yamlint --format parsable --strict -c=tests/yamllint.yaml .
