---
name: Validate definitions

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Device-Type Tests
        run: pytest --tb=line -v
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_EXCLUDE: (.*/)?(LICENSE|configuration/.*)

          #MARKDOWN_CONFIG_FILE: .markdown-lint.yaml
          YAML_CONFIG_FILE: tests/yamllint.yaml
